export const categories = ['한식', '중식', '일식', '양식'];

export const menus = [
  // --- 한식 (Korean) ---
  { id: 'k1', name: '김치찌개', category: '한식', cal: 450, allergens: ['돼지고기', '대두'], image: '/김치찌개.png' },
  { id: 'k2', name: '된장찌개', category: '한식', cal: 350, allergens: ['대두', '해산물'], image: '/ehlswkd.jpg' },
  { id: 'k3', name: '순두부찌개', category: '한식', cal: 400, allergens: ['대두', '해산물', '계란'], image: '/순두부찌개.png' },
  { id: 'k4', name: '청국장', category: '한식', cal: 400, allergens: ['대두'], image: '/청국장.png' },
  { id: 'k5', name: '비지찌개', category: '한식', cal: 420, allergens: ['대두', '돼지고기'], image: '/비지찌개.png' },
  { id: 'k6', name: '부대찌개', category: '한식', cal: 700, allergens: ['돼지고기', '밀', '대두'], image: '/부대찌개.png' },
  { id: 'k7', name: '동태찌개', category: '한식', cal: 380, allergens: ['해산물', '대두'], image: '/동태찌개.png' },
  { id: 'k8', name: '제육볶음', category: '한식', cal: 600, allergens: ['돼지고기', '대두'], image: '/wpdbr.jpg.png' },
  { id: 'k9', name: '소불고기', category: '한식', cal: 550, allergens: ['소고기', '대두'], image: '/소불고기.png' },
  { id: 'k10', name: '돼지불백', category: '한식', cal: 580, allergens: ['돼지고기', '대두'], image: '/돼지불백.png' },
  { id: 'k11', name: '오징어볶음', category: '한식', cal: 450, allergens: ['해산물'], image: '/오징어 볶음.png' },
  { id: 'k12', name: '낙지볶음', category: '한식', cal: 430, allergens: ['해산물'], image: '/낚지 볶음.png' },
  { id: 'k13', name: '주꾸미볶음', category: '한식', cal: 440, allergens: ['해산물'], image: '/쭈꾸미 볶음.png' },
  { id: 'k14', name: '닭볶음탕', category: '한식', cal: 650, allergens: ['닭고기'], image: '/닭볶음탕.png' },
  { id: 'k15', name: '찜닭', category: '한식', cal: 700, allergens: ['닭고기', '대두'], image: '/찜닭.png' },
  { id: 'k16', name: '떡볶이', category: '한식', cal: 500, allergens: ['밀'], image: '/떡볶이.png' },
  { id: 'k17', name: '순대볶음', category: '한식', cal: 600, allergens: ['돼지고기'], image: '/순대 볶음.png' },
  { id: 'k18', name: '모둠튀김', category: '한식', cal: 800, allergens: ['밀', '해산물'], image: '/모둠튀김.png' },
  { id: 'k19', name: '보쌈', category: '한식', cal: 850, allergens: ['돼지고기'], image: '/qhTKa.jpg.png' },
  { id: 'k20', name: '족발', category: '한식', cal: 900, allergens: ['돼지고기', '대두'], image: '/whrqkf.jpg.png' },
  { id: 'k21', name: '매운족발', category: '한식', cal: 950, allergens: ['돼지고기', '대두'], image: '/매운 족발.png' },
  { id: 'k22', name: '갈비탕', category: '한식', cal: 600, allergens: ['소고기'], image: '/갈비탕.png' },
  { id: 'k23', name: '설렁탕', category: '한식', cal: 500, allergens: ['소고기'], image: '/설렁탕.png' },
  { id: 'k24', name: '곰탕', category: '한식', cal: 500, allergens: ['소고기'], image: '/곰탕.png' },
  { id: 'k25', name: '도가니탕', category: '한식', cal: 550, allergens: ['소고기'], image: '/도가니탕.png' },
  { id: 'k26', name: '육개장', category: '한식', cal: 550, allergens: ['소고기'], image: '/dbrrowkd.jpg.png' },
  { id: 'k27', name: '해장국', category: '한식', cal: 600, allergens: ['돼지고기', '소고기'], image: '/해장국.png' },
  { id: 'k28', name: '감자탕', category: '한식', cal: 750, allergens: ['돼지고기'], image: '/감자탕.png' },
  { id: 'k29', name: '뼈해장국', category: '한식', cal: 700, allergens: ['돼지고기'], image: '/뼈해장국.png' },
  { id: 'k30', name: '추어탕', category: '한식', cal: 500, allergens: ['해산물'], image: '/추어탕.png' },
  { id: 'k31', name: '삼계탕', category: '한식', cal: 900, allergens: ['닭고기'], image: '/삼계탕.png' },
  { id: 'k32', name: '물냉면', category: '한식', cal: 450, allergens: ['밀', '계란', '소고기'], image: '/sodaus.jpg.png' },
  { id: 'k33', name: '비빔냉면', category: '한식', cal: 500, allergens: ['밀', '계란'], image: '/비빔냉면.png' },
  { id: 'k35', name: '콩국수', category: '한식', cal: 480, allergens: ['밀', '대두'], image: '/콩국수.png' },
  { id: 'k36', name: '칼국수', category: '한식', cal: 500, allergens: ['밀', '해산물'], image: '/칼국수.png' },
  { id: 'k37', name: '수제비', category: '한식', cal: 480, allergens: ['밀', '해산물'], image: '/수제비.png' },
  { id: 'k38', name: '잔치국수', category: '한식', cal: 420, allergens: ['밀', '계란'], image: '/잔치국수.png' },
  { id: 'k39', name: '비빔국수', category: '한식', cal: 480, allergens: ['밀', '계란'], image: '/비빔국수.png' },
  { id: 'k40', name: '삼겹살구이', category: '한식', cal: 850, allergens: ['돼지고기'], image: '/삽겹살 구이.png' },
  { id: 'k41', name: '돼지갈비구이', category: '한식', cal: 800, allergens: ['돼지고기', '대두'], image: '/돼지갈비.png' },
  { id: 'k42', name: '한우구이', category: '한식', cal: 700, allergens: ['소고기'], image: '/hanwoo.jpg' },
  { id: 'k43', name: '육회', category: '한식', cal: 350, allergens: ['소고기', '계란'], image: '/육회.png' },
  { id: 'k44', name: '육회비빔밥', category: '한식', cal: 600, allergens: ['소고기', '계란'], image: '/육회비빔밥.png' },
  { id: 'k45', name: '산채비빔밥', category: '한식', cal: 500, allergens: ['계란'], image: '/산채 비빔밥.png' },
  { id: 'k46', name: '돌솥비빔밥', category: '한식', cal: 550, allergens: ['계란', '소고기'], image: '/돌솥비빔밥.png' },
  { id: 'k47', name: '갈치조림', category: '한식', cal: 550, allergens: ['해산물', '대두'], image: '/갈치조림.png' },
  { id: 'k48', name: '고등어조림', category: '한식', cal: 600, allergens: ['해산물', '대두'], image: '/고등어 조림.png' },
  { id: 'k49', name: '아구찜', category: '한식', cal: 650, allergens: ['해산물'], image: '/아구찜.png' },
  { id: 'k50', name: '해물찜', category: '한식', cal: 600, allergens: ['해산물'], image: '/해물찜.png' },
  { id: 'k51', name: '해물파전', category: '한식', cal: 600, allergens: ['밀', '해산물', '계란'], image: '/해물파전.png' },
  { id: 'k52', name: '김치전', category: '한식', cal: 500, allergens: ['밀'], image: '/김치전.png' },
  { id: 'k53', name: '감자전', category: '한식', cal: 450, allergens: ['밀'], image: '/감자전.png' },

  // --- 중식 (Chinese) ---
  { id: 'c1', name: '짜장면', category: '중식', cal: 800, allergens: ['밀', '돼지고기', '대두'], image: '/짜장면.png' },
  { id: 'c2', name: '짜장밥', category: '중식', cal: 750, allergens: ['돼지고기', '대두'], image: '/짜장밥.png' },
  { id: 'c3', name: '짬뽕밥', category: '중식', cal: 700, allergens: ['해산물', '돼지고기'], image: '/짬뽕밥.png' },
  { id: 'c4', name: '짬뽕', category: '중식', cal: 750, allergens: ['밀', '해산물', '돼지고기'], image: '/짬뽕.png' },
  { id: 'c5', name: '볶음밥', category: '중식', cal: 750, allergens: ['계란', '새우'], image: '/볶음밥.png' },
  { id: 'c6', name: '잡채밥', category: '중식', cal: 700, allergens: ['돼지고기', '대두'], image: '/잡채밥.png' },
  { id: 'c7', name: '마파두부밥', category: '중식', cal: 650, allergens: ['대두', '돼지고기'], image: '/마파두부밥.png' },
  { id: 'c8', name: '유산슬밥', category: '중식', cal: 650, allergens: ['해산물', '돼지고기'], image: '/유산슬밥.png' },
  { id: 'c9', name: '탕수육', category: '중식', cal: 900, allergens: ['돼지고기', '밀'], image: '/탕수육.png' },
  { id: 'c10', name: '꿔바로우', category: '중식', cal: 950, allergens: ['돼지고기', '밀'], image: '/꿔바로우.png' },
  { id: 'c11', name: '사천탕수육', category: '중식', cal: 950, allergens: ['돼지고기', '밀'], image: '/사천탕수육.png' },
  { id: 'c12', name: '마라탕', category: '중식', cal: 800, allergens: ['대두', '땅콩', '소고기', '해산물'], image: '/마라탕.png' },
  { id: 'c13', name: '마라샹궈', category: '중식', cal: 900, allergens: ['대두', '땅콩', '소고기', '해산물'], image: '/마라샹궈.png' },
  { id: 'c14', name: '마라롱샤', category: '중식', cal: 600, allergens: ['해산물'], image: '/마라롱샤.png' },
  { id: 'c15', name: '유린기', category: '중식', cal: 800, allergens: ['닭고기', '밀'], image: '/유린기.png' },
  { id: 'c16', name: '깐풍기', category: '중식', cal: 850, allergens: ['닭고기', '밀'], image: '/깐풍기.png' },
  { id: 'c17', name: '크림새우', category: '중식', cal: 950, allergens: ['해산물', '유제품', '밀'], image: '/크림새우.png' },
  { id: 'c18', name: '칠리새우', category: '중식', cal: 900, allergens: ['해산물', '밀'], image: '/칠리새우.png' },
  { id: 'c19', name: '고추잡채', category: '중식', cal: 650, allergens: ['돼지고기'], image: '/고추잡채.png' },
  { id: 'c20', name: '꽃빵', category: '중식', cal: 300, allergens: ['밀'], image: '/꽃빵.png' },
  { id: 'c21', name: '양장피', category: '중식', cal: 500, allergens: ['해산물', '돼지고기', '겨자'], image: '/양장피.png' },
  { id: 'c22', name: '팔보채', category: '중식', cal: 550, allergens: ['해산물', '돼지고기'], image: '/팔보채.png' },
  { id: 'c23', name: '울면', category: '중식', cal: 600, allergens: ['밀', '해산물', '계란'], image: '/울면.png' },
  { id: 'c24', name: '멘보샤', category: '중식', cal: 800, allergens: ['밀', '해산물'], image: '/멘보샤.png' },
  { id: 'c25', name: '군만두', category: '중식', cal: 600, allergens: ['밀', '돼지고기'], image: '/군만두.png' },
  { id: 'c26', name: '물만두', category: '중식', cal: 500, allergens: ['밀', '돼지고기'], image: '/물만두.png' },
  { id: 'c27', name: '딤섬', category: '중식', cal: 400, allergens: ['밀', '해산물', '돼지고기'], image: '/딤섬.png' },
  { id: 'c28', name: '소룡포', category: '중식', cal: 500, allergens: ['밀', '돼지고기'], image: '/소롱포.png' },
  { id: 'c29', name: '토마토달걀볶음', category: '중식', cal: 350, allergens: ['계란'], image: '/토마토 달걀 볶음.png' },
  { id: 'c30', name: '탄탄면', category: '중식', cal: 700, allergens: ['밀', '땅콩', '돼지고기'], image: '/탄탄면.png' },
  { id: 'c31', name: '우육면', category: '중식', cal: 650, allergens: ['밀', '소고기'], image: '/우육면.png' },
  { id: 'c32', name: '동파육', category: '중식', cal: 950, allergens: ['돼지고기', '대두'], image: '/동파육.png' },

  // --- 일식 (Japanese) ---
  { id: 'j1', name: '스시', category: '일식', cal: 500, allergens: ['해산물'], image: '/스시.png' },
  { id: 'j2', name: '사시미', category: '일식', cal: 300, allergens: ['해산물'], image: '/사시미.png' },
  { id: 'j3', name: '돈카츠', category: '일식', cal: 850, allergens: ['돼지고기', '밀', '계란'], image: '/돈카츠.png' },
  { id: 'j4', name: '규동', category: '일식', cal: 700, allergens: ['소고기', '대두', '계란'], image: '/규동.png' },
  { id: 'j5', name: '가츠동', category: '일식', cal: 850, allergens: ['돼지고기', '밀', '계란', '대두'], image: '/가츠동.png' },
  { id: 'j6', name: '샤브샤브', category: '일식', cal: 500, allergens: ['소고기'], image: '/샤브샤브.png' },
  { id: 'j24', name: '야끼니꾸', category: '일식', cal: 700, allergens: ['소고기', '대두'], image: '/야끼니꾸.png' },
  { id: 'j25', name: '가라아게', category: '일식', cal: 650, allergens: ['닭고기', '밀'], image: '/가라아게.png' },
  { id: 'j26', name: '쿠시카츠', category: '일식', cal: 700, allergens: ['돼지고기', '밀'], image: '/쿠시카츠.png' },
  { id: 'j27', name: '명란밥', category: '일식', cal: 400, allergens: ['해산물'], image: '/명란밥.png' },
  { id: 'j28', name: '오차즈케', category: '일식', cal: 350, allergens: ['해산물'], image: '/오차즈케.png' },
  { id: 'j30', name: '가츠샌드', category: '일식', cal: 600, allergens: ['밀', '돼지고기'], image: '/가츠샌드.png' },

  // --- 양식 및 세계 요리 (Western & Global) ---
  { id: 'w1', name: '피자', category: '양식', cal: 900, allergens: ['밀', '유제품'], image: '/피자.png' },
  { id: 'w2', name: '알리오올리오', category: '양식', cal: 600, allergens: ['밀'], image: '/알리오올리오.png' },
  { id: 'w3', name: '봉골레', category: '양식', cal: 650, allergens: ['밀', '해산물'], image: '/봉골레.png' },
  { id: 'w4', name: '로제파스타', category: '양식', cal: 750, allergens: ['밀', '유제품', '해산물'], image: '/로제파스타.png' },
  { id: 'w5', name: '토마토파스타', category: '양식', cal: 600, allergens: ['밀'], image: '/토마토 파스타.png' },
  { id: 'w6', name: '미트볼파스타', category: '양식', cal: 800, allergens: ['밀', '소고기', '돼지고기'], image: '/미트볼 파스타.png' },
  { id: 'w7', name: '투움바파스타', category: '양식', cal: 950, allergens: ['밀', '유제품', '해산물'], image: '/투움바 파스타.png' },
  { id: 'w8', name: '등심스테이크', category: '양식', cal: 800, allergens: ['소고기'], image: '/등심스테이크.png' },
  { id: 'w9', name: '안심스테이크', category: '양식', cal: 700, allergens: ['소고기'], image: '/안심스테이크.png' },
  { id: 'w10', name: '바비큐폭립', category: '양식', cal: 1000, allergens: ['돼지고기'], image: '/바베큐폭립.png' },
  { id: 'w11', name: '햄버거', category: '양식', cal: 700, allergens: ['밀', '소고기', '유제품'], image: '/햄버거.png' },
  { id: 'w12', name: '샌드위치', category: '양식', cal: 500, allergens: ['밀', '계란'], image: '/샌드위치.png' },
  { id: 'w13', name: '잠봉뵈르', category: '양식', cal: 650, allergens: ['밀', '유제품', '돼지고기'], image: '/잠봉뵈르.png' },
  { id: 'w14', name: '라자냐', category: '양식', cal: 850, allergens: ['밀', '유제품', '소고기'], image: '/라자냐.png' },
  { id: 'w15', name: '뇨끼', category: '양식', cal: 700, allergens: ['밀', '유제품'], image: '/뇨끼.png' },
  { id: 'w16', name: '크림리조또', category: '양식', cal: 800, allergens: ['유제품'], image: '/크림리조또.png' },
  { id: 'w17', name: '토마토리조또', category: '양식', cal: 650, allergens: ['해산물'], image: '/토마토 리조또.png' },
  { id: 'w18', name: '오믈렛', category: '양식', cal: 450, allergens: ['계란', '유제품'], image: '/오믈렛.png' },
  { id: 'w19', name: '에그베네딕트', category: '양식', cal: 600, allergens: ['계란', '밀', '유제품', '돼지고기'], image: '/애그베네딕트.png' },
  { id: 'w20', name: '프렌치토스트', category: '양식', cal: 550, allergens: ['밀', '계란', '유제품'], image: '/프렌치토스트.png' },
  { id: 'w21', name: '감바스', category: '양식', cal: 700, allergens: ['해산물', '새우'], image: '/감바스.png' },
  { id: 'w22', name: '타코', category: '양식', cal: 500, allergens: ['밀', '소고기', '돼지고기'], image: '/타코.png' },
  { id: 'w23', name: '쌀국수', category: '양식', cal: 450, allergens: ['소고기'], image: '/쌀국수.png' },
  { id: 'w24', name: '분짜', category: '양식', cal: 600, allergens: ['돼지고기'], image: '/분짜.png' },
  { id: 'w25', name: '팟타이', category: '양식', cal: 650, allergens: ['해산물', '계란', '땅콩'], image: '/팟타이.png' },
  { id: 'w26', name: '똠얌꿍', category: '양식', cal: 500, allergens: ['해산물'], image: '/똠양꿍.png' },
  { id: 'w27', name: '카레', category: '양식', cal: 650, allergens: ['돼지고기', '소고기'], image: '/카레.png' }
];